- name: Run tests
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'
        run:
          - make test-client
          - make test-server

name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows]
        arch: [x86_64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.17.3'
      - run: make release-client
      - run: make release-server
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: bin/*

      - name: Run tests
        uses: actions/setup-go@v1
        with:
          go-version: '1.17.3'
        run:
          - make test-client
          - make test-server
