name: Build

on:
  push:

jobs:
  build:
    env:
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [386, amd64, arm64, arm]
        exclude:
          - os: darwin
            arch: arm
          - os: darwin
            arch: 386
    steps:
      - name: Checks-out
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'
      - run: make release-client
      - run: make release-server