name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install go-bindata
        run: go get -u github.com/go-bindata/go-bindata/...
      - name: Build for all platforms
        run: |
          go-bindata -o assets/client/assets/assets.go -pkg assets -ignore *.go assets/client/...
          go-bindata -o assets/server/assets/assets.go -pkg assets -ignore *.go assets/server/...
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o bin/ngrok_darwin_amd64
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/ngrok_linux_amd64
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o bin/ngrok_windows_amd64.exe
      - uses: actions/upload-artifact@v2
        with:
          name: Release Artifacts
          path: bin/*
      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: |
            Release v1.0.0
          draft: false
          prerelease: false
